export default function Terms() {
    return (
        <div className="coming-soon" style={{ display: 'flex', flexDirection: 'column', gap: '2rem', padding: '4rem' }}>
            <div className="coming-soon__header">
                <div className="coming-soon__hero" style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
                    <h1>Terms and Conditions for Users</h1>
                    <p>Please review the terms of service contained herein carefully. By clicking “I agree” or accessing and/or using any of the Services provided by TimeVerse, you have read, understood, and accepted all of the following Terms, as well as all of the terms which are incorporated herein by reference.</p>

                    <h2>Rights and Obligations</h2>
                    <p>The following terms of service (the “Terms”) constitute a binding agreement between you and TimeVerse Labs GmbH, a company registered under the laws of Switzerland, with registered address in Zeughausstrasse 2 8730 Uznach (“TimeVerse”), in connection with your use of the Service.</p>
                    <p>These Terms also govern your interaction with any websites, platform or application (“Platform & Apps”) owned or operated by TimeVerse and more generally your use of any TimeVerse products or services (all together the “Services”).</p>
                    <p>By accessing and/or using the Services, You have read, understood, and accepted all of the following Terms and agree to be legally bound by these Terms, in their most recent version. You further represent and warrant that: (i) you are of legal age to enter into a binding agreement; (ii) if you are not of legal age to enter into a binding agreement, you are above 16 (sixteen) years old and your parents or legal guardians have provided consent; and (iii) if you represent a corporation, governmental organisation or other legal entity, you have the right, power and authority to enter into these Terms on behalf of such corporation, governmental organisation or other legal entity and to legally bind it to these Terms.</p>
                    <p>Your access and/or use of the Services is contingent upon your acceptance of these Terms.</p>
                    <p>TimeVerse may amend these Terms at any time. Amendments will be effective 14 (fourteen) days after the modified terms and conditions have been posted on the App or Sites, except for amendments that relate to new features or made for legal reasons, which will become effective immediately. If you do not agree to such modified terms, you should discontinue your use of the Services.</p>

                    <h2>Users Eligible to Participate</h2>
                    <p>If you want to use certain Services, you will have to create an account, and you will also need access to an Internet connection and an e-mail address.</p>
                    <p>You agree that you will not disclose your account password to anyone and you will notify us immediately of any unauthorised use of your account. You are responsible for all activities that occur under your account, whether or not known to you.</p>
                    <p>You may terminate your account at any time. Upon termination of any Services or your account, the following provisions of these Terms will survive: Intellectual Property, Content & Content Rights, Limit of Use & Prohibited Conduct, Data Protection, Termination, Limitation of Liability, Indemnification, Miscellaneous.</p>
                    <p>Only persons of legal age or persons above 16 (sixteen) years old whose parents or legal guardians have provided consent to the use of the Services are allowed participation. With your participation in a Service, you represent that you are of legal age and of legal capacity (or, if you are a minor, that you are above 16 (sixteen) years old and that a parent or legal guardian has provided consent). TimeVerse is entitled to request at any time a written proof of your age or the written consent of a parent or legal guardian. If you are a minor, as soon as you use the Service after you become of legal age, then all agreements in connection with you concluded before achieving legal age are deemed approved, provided that you do not revoke the approval toward TimeVerse within two weeks upon reaching legal age.</p>
                    <p>To the extent permitted under applicable law, TimeVerse declines any responsibility regarding any activities conducted by a minor with or without the permission of a parent or legal guardian. If you are a parent or legal guardian and you give your permission for your child to register for one of the services, you thereby agree to the terms relating to use of the services by your child.</p>

                    <h2>Intellectual Property</h2>
                    <p>You acknowledge and agree that the Services are the property of TimeVerse or its licensors and that they are protected under national and international law and particularly by copyright, trademark, and other laws. The unauthorised dissemination, copying, deletion or any other violation of intellectual property rights and copyrights of TimeVerse are punishable under both civil and criminal law.</p>
                    <p>Subject to your compliance with these Terms, TimeVerse grants you a limited, non-exclusive, non-transferable, non-sublicensable licence to access and use the Services. Except as expressly permitted in these Terms or under applicable law, you may not: (i) copy, modify, or create derivative works based on the Services; (ii) distribute, transfer, sublicense, lease, lend, or rent the Services to any third party; (iii) reverse engineer, decompile, or disassemble the Services; or (iv) make the functionality of the Services available to multiple users through any means. TimeVerse reserves all rights in and to the Services not expressly granted to you under these Terms.</p>
                    <p>You acknowledge and agree that TimeVerse its trademark, service mark, logo and graphics are the registered trademarks or trademarks of TimeVerse.</p>

                    <h2>Digital Token</h2>
                    <p>The token represents only the right of ownership of a fraction of the Real World Asset (“Digital Token”).</p>
                    <p>The Services may allow you to collect and have in custody the Digital Tokens through the use of a third-party service provider.</p>
                    <p>Custody and Digital Tokens are provided on a “as is” and “as available” basis, without any warranty, except where prohibited under applicable law.</p>
                    <p>The Services may further allow you to purchase the Digital Tokens of the Platform & Apps. All sales by TimeVerse are final and TimeVerse will not permit exchanges or refunds for any unused token once the transaction has been made.</p>
                    <p>Digital tokens can be used to unlock additional features and functionalities of the Services, take parts in Events provided by TimeVerse or to receive discounts in relation with the offered Services from time to time (the “Offerings”). TimeVerse is entitled to change the terms of such Offerings at any time, and to reduce and/or increase the Digital Assets required for such Offerings.</p>
                    <p>Any Digital Token balance does not reflect any stored value and you agree that the Digital Token has no monetary value.</p>
                    <p>Generally, TimeVerse has the right to offer, modify, eliminate, and/or terminate any of the Services, or any portion thereof, at any time, without notice or liability to you.</p>

                    <h2>Custody of Digital Tokens</h2>
                    <p>TimeVerse use a third-party service that allows you to put in custody certain supported Digital Tokens.</p>
                    <p>The custodian service is only for use with Digital Tokens that TimeVerse may explicitly decide to support now or in the future at its sole discretion. TimeVerse has no obligation to support any other Digital Tokens. TimeVerse takes no responsibility or liability in connection with any attempt to use its custodian service for Digital Tokens other than the supported Digital Tokens.</p>
                    <p>By accessing and/or using the custodian service, you acknowledge and agree that TimeVerse cannot guarantee the confirmation of any transaction on any blockchain network. Neither TimeVerse has control over any blockchain network.</p>
                    <p>By accessing and/or using the custodian service, you represent and warrant that (i) you fully understand and have significant experience of digital assets, blockchain systems and services, and (ii) you fully understand the mechanics related to the use of Digital Tokens (including with respect to their storage).</p>
                    <p>The Digital Token used within the Platform & Apps cannot be used outside the TimeVerse Network.</p>

                    <h2>Custody of the Real World Asset</h2>
                    <p>TimeVerse will appoint third-party providers to keep in custody the Real World Asset as described in the Contract of Sale between Buyers and Sellers represented by the token. TimeVerse will assure a proper custody and act as a bailee according to art. 472 ff. Code of obligations.</p>
                    <p>You accept and agree to comply with the provisions of the co-ownership agreement entered into between the owners of the wallets which hold the Digital Token representing the right of ownership of the Real World Asset (“Co-ownership Agreement”).</p>

                    <h2>Payment</h2>
                    <p>TimeVerse will use the money collected with the sale of the Digital Tokens for the purchase of the Real World Asset within 60 days, as foreseen by Swiss law. This activity is not subject to FINMA supervision as far as no interest is paid on the deposits.</p>
                    <p>In case TimeVerse is not in measure to execute the acquisition of the Real World Asset, the money in custody will be returned within 60 days from the payment.</p>
                    <p>If You use our Platform, You acknowledge that in certain cases, users in Switzerland, the European Economic Area (EEA) and the UK are protected under certain consumer laws. This includes a 14-day “right of withdrawal” when you buy a share of the Real World Asset. You will fully cooperate with us in this process. TimeVerse agrees to repurchase any share of the Real World Asset that the Buyer wishes to withdraw.</p>

                    <h2>Limits of Use & Prohibited Conduct</h2>
                    <p>TimeVerse provides the services solely for use in accordance with these Terms. Automated use is prohibited. Only the official App and Sites provided by TimeVerse must be used to connect to the Services. You may not create, support, host, link or provide any other options, which can be used by another person to use the services.</p>
                    <p>You are not entitled to use any means, mechanisms or software in connection with any service provided by TimeVerse which can disturb the function and the Services’ process. You may not undertake any action, which can result in an unreasonable or excess load of the technical capacities of TimeVerse. In particular, you may not block, overwrite or modify the contents generated by TimeVerse without the prior written consent of TimeVerse.</p>
                    <p>You may not add elements to the Services or to change, delete or modify in any other manner any service elements without the prior written consent of TimeVerse. In particular, you may not copy, remove or otherwise utilise any graphic elements or to try to decompile the source code of services.</p>
                    <p>You may not utilise any ancillary means, which maliciously modify the service score or the service process (specifically so-called “bots”, “hacks”, “change VPN” or “cheats”) nor promote their use toward third parties. You may not intentionally use third party software or other applications nor program errors for your own benefit.</p>
                    <p>Further, you agree that in conjunction with your use of the Services you will not finance any unlawful or inappropriate Content.</p>
                    <p>You agree that in conjunction with your use of the Services, you will maintain safe and appropriate contact with any third party, if any, and other people in the real world. You will not harass, threaten or otherwise violate the legal rights of others. If you have a dispute with any third party relating to your use of Services, you release TimeVerse (and its officers, directors, agents, subsidiaries, joint ventures, and employees) from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.</p>
                    <p>Although TimeVerse is not obligated to monitor access to or use of the Services or to review the payment executed to third parties, it may have the right or the duty to do so for the purpose of operating the Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. TimeVerse reserves the right to remove or disable access to any Content, at any time and without notice. TimeVerse may block any transaction it considers to be objectionable or in violation of these Terms. TimeVerse has the right to investigate violations of these Terms or conduct that affects the Services. TimeVerse may also consult and cooperate with law enforcement authorities to prosecute users and others who violate the law.</p>
                    <p>Any attempt by you to disrupt or interfere with the Services, including without limitation undermining or manipulating the legitimate operation of any Site or App, is a breach of these Terms and may be a breach or violation of criminal and civil laws.</p>
                    <p>TimeVerse is entitled to take reasonable measures to prevent or curtail violations against this Section 5. In addition, in case of such violations, TimeVerse is entitled to block your account.</p>

                    <h2>Service Limitations and Modifications</h2>
                    <p>TimeVerse will make reasonable efforts to keep the Services operational. However, certain technical difficulties or maintenance may, from time to time, result in temporary interruptions. To the extent permissible under applicable law, TimeVerse reserves the right, periodically and at any time, to modify or discontinue, temporarily or permanently, functions and features of the Services, with or without notice, without liability to you, for any interruption, modification, or discontinuation of the Services or any function or feature thereof.</p>

                    <h2>Data Protection</h2>
                    <p>In order to provide you with the Services, you acknowledge and agree that TimeVerse may collect, store and process your personal data and/or information. By accessing and/or using the Services, you have read, understood, and accepted the terms of TimeVerse’s Privacy Policy, and you acknowledge and agree that TimeVerse may use such data and/or information in accordance with the terms of its privacy policy.</p>

                    <h2>Termination</h2>
                    <p>The agreements between user and TimeVerse (e.g. these Terms) are concluded for an unspecified time unless otherwise agreed in writing.</p>
                    <p>TimeVerse may terminate these Terms or suspend your access to the Services or account at any time, including, without limitation, in the event of your alleged or actual misuse of the Services or breach of these Terms.</p>

                    <h2>Limitation of Liability</h2>
                    <p>In no event will TimeVerse, its officers, shareholders, employees, agents, directors, subsidiaries, affiliates, successors, assigns, suppliers, or licensors be liable for any loss or damages, including without limitation, direct, indirect, special, consequential, or punitive loss or damages, arising from or related to your use of the Services, whether in an action of contract, tort or otherwise, and regardless of whether such damages were foreseeable and whether or not TimeVerse was advised of the possibility of such damages.</p>
                    <p>Without limiting the generality of the foregoing, TimeVerse takes no responsibility for and will not be liable for any financial or other loss or damages arising from or related to the use of the Services, including, without limitation, to any of the following: (i) technical failure, malfunction or shutdown; (ii) server failure, hacks or unavailability; (iii) data loss; (iv) stolen, lost, or unauthorised use of your means of authentication; (v) errors calculating network fees; (vi) corrupted data on TimeVerse’s servers; (vii) failure to update or provide correct information; (viii) “phishing” or other websites masquerading as TimeVerse; (ix) delays, interruption or loss of services; (x) loss of business or goodwill.</p>
                    <p>The Services support or are integrated with third party services, including third party payment services. TimeVerse takes no responsibility for any third party services and will not be liable for any loss or damages caused by such third party services.</p>
                    <p>The Services are provided on an “as is” and “as available” basis without any representation or warranty of any kind, whether express or implied, to the maximum extent permitted by applicable laws. TimeVerse disclaims any implied warranties of title, merchantability, fitness for a particular purpose and/or non-infringement. You understand that TimeVerse does not screen or inquire into the background of any users of the services.</p>

                    <h2>Indemnification</h2>
                    <p>To the fullest extent permitted under applicable laws, You agree to hold harmless and indemnify TimeVerse, its officers, shareholders, employees, agents, directors, subsidiaries, affiliates, successors, assigns, suppliers, or licensors from and against all third party claims and all liabilities, damages, assessments, losses, costs, or expenses (including reasonable attorney fees) resulting from or arising out of: (i) your alleged or actual breach of these Terms, including, without limitation, Your express representations and warranties; (ii) your alleged or actual use or misuse of the Services; and (ii) your alleged or actual infringement or violation of any laws or of the rights of a third party.</p>

                    <h2>Miscellaneous</h2>
                    <h3>Entire Agreement</h3>
                    <p>These Terms constitute all the terms and conditions agreed upon between you and TimeVerse and supersede any prior agreements in relation to the subject matter of these Terms, whether written or oral.</p>
                    <h3>Severability and Waiver</h3>
                    <p>Unless as otherwise stated in these Terms, should any provision of these Terms be held totally or partially invalid or unenforceable, such invalidity or unenforceability shall not in any manner affect or render invalid or unenforceable the remaining provisions of these Terms, and the application of that provision shall be enforced to the extent permitted by applicable laws. The failure of TimeVerse to exercise or enforce any of the rights or provisions of these Terms shall not be considered as a waiver of TimeVerse’s rights to do so.</p>
                    <h3>Assignment</h3>
                    <p>TimeVerse may assign these Terms and/or delegate any of its obligations hereunder, in whole or in part. You may not assign these Terms or any part of them, nor transfer or sub-license your rights under these Terms to any third party.</p>
                    <h3>No Partnership</h3>
                    <p>Nothing contained in this Agreement shall be deemed or construed to create a principal and agent, partnership or joint venture relationship between you and TimeVerse.</p>
                    <h3>Force Majeure</h3>
                    <p>TimeVerse will not be deemed in default of these Terms to the extent that performance of its obligations is delayed or prevented by reason of any external force including, without limitation, war, insurrections, bank failures, strikes, fires, floods, earthquakes, labor disputes, epidemics, governmental regulations, freight embargoes, natural disaster, act of government or any other cause beyond TimeVerse’s reasonable control.</p>
                    <h3>Governing Law and Jurisdiction</h3>
                    <p>These Terms are subject to and governed by Swiss law to the exclusion of Swiss international private law and any international treaties. All disputes arising from or under these Terms shall be subject to the exclusive jurisdiction of the competent courts of Lugano, Switzerland.</p>
                </div>
            </div>
        </div>
    );
                    
};